version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: wikitabia-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      wikitabia:
    ports:
      - "${DB_PORT}:5432"

  wikitabia-server:
    image: ${REGISTRY_URL}/${WIKITABIA_SERVER_REPO}/${WIKITABIA_SERVER_IMAGE_NAME}:${WIKITABIA_SERVER_IMAGE_TAG}
    container_name: wikitabia-server
    restart: always
    environment:
      spring.datasource.url: "jdbc:postgresql://postgres:5432/${DB_NAME}"
      spring.datasource.username: ${DB_USER}
      spring.datasource.password: ${DB_PASS}
    depends_on:
      - postgres
    networks:
      wikitabia:
    ports:
      - "${WIKITABIA_SERVER_OUTER_PORT}:8080"

volumes:
  postgres:

networks:
  wikitabia:
